name: Contract Test with Docker CLI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Pull Docker dependencies
        run: docker compose pull

      - name: Start dependencies
        run: docker compose up -d

      - name: Wait for Kafka broker
        run: |
          echo "Waiting for Kafka broker..."
          for i in {1..60}; do
            if nc -z localhost 9092; then
              echo "Kafka broker is ready"
              break
            fi
            if [ $i -eq 60 ]; then
              echo "Kafka broker failed to start"
              docker compose logs
              exit 1
            fi
            sleep 2
          done

      - name: Start application
        run: |
          nohup ./gradlew bootRun > app.log 2>&1 &
          echo $! > app.pid

      - name: Wait for application
        run: |
          echo "Waiting for application..."
          for i in {1..60}; do
            if nc -z localhost 8085; then
              echo "Application is ready"
              sleep 5
              break
            fi
            if [ $i -eq 60 ]; then
              echo "Application failed to start"
              cat app.log
              exit 1
            fi
            sleep 2
          done

      - name: Run Specmatic contract tests
        run: |
          docker run --network avro-app-network \
            -v "$PWD/specmatic.yaml:/usr/src/app/specmatic.yaml" \
            -v "$PWD/api-specs:/usr/src/app/api-specs" \
            -v "$PWD/build:/usr/src/app/build" \
            --rm specmatic/specmatic-kafka:1.0.1 test \
            --broker=broker:9093 \
            --schema-registry-url=http://schema-registry:8085 \
            --schema-registry-kind=CONFLUENT

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contract-test-reports
          path: build/reports/

      - name: Show application logs on failure
        if: failure()
        run: cat app.log || echo "No application logs found"

      - name: Stop application
        if: always()
        run: |
          if [ -f app.pid ]; then
            kill $(cat app.pid) || true
          fi
          pkill -f 'bootRun' || true
          sleep 2
          pkill -9 -f 'bootRun' || true

      - name: Stop containers
        if: always()
        run: docker compose down -v

